"use client";

import { useState, useEffect } from "react";
import TopNav from "@/components/TopNav";
import type { ClientProfile, QAReport } from "@/lib/pipeline";

type InputMode = "paste" | "upload";

export default function QAPage() {
  const [mode, setMode] = useState<InputMode>("paste");
  const [htmlContent, setHtmlContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [report, setReport] = useState<QAReport | null>(null);
  const [expandedPass, setExpandedPass] = useState<string | null>(null);
  const [clients, setClients] = useState<ClientProfile[]>([]);
  const [attachClientId, setAttachClientId] = useState("");
  const [authChecked, setAuthChecked] = useState(false);

  // Role gate: only rep or dev
  useEffect(() => {
    try {
      const cookie = document.cookie.split("; ").find((c) => c.startsWith("dc_session="));
      if (cookie) {
        const val = JSON.parse(decodeURIComponent(cookie.split("=")[1]));
        if (val.role === "rep" || val.role === "dev") {
          setAuthChecked(true);
          return;
        }
      }
    } catch { /* ignore */ }
    window.location.href = "/login";
  }, []);

  useEffect(() => {
    if (!authChecked) return;
    async function loadClients() {
      try {
        const res = await fetch("/api/clients");
        const data = await res.json();
        setClients(data.clients || []);
      } catch {
        /* ignore */
      }
    }
    loadClients();
  }, [authChecked]);

  async function runQA() {
    if (!htmlContent.trim()) return;
    setLoading(true);
    setReport(null);
    setLoadingStep(0);

    for (let i = 1; i <= 4; i++) {
      await new Promise((r) => setTimeout(r, 600));
      setLoadingStep(i);
    }

    try {
      const res = await fetch("/api/qa/standalone", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ htmlContent }),
      });
      const data = await res.json();
      setReport(data.report);
    } catch {
      /* handle error */
    }
    setLoading(false);
  }

  function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      setHtmlContent((ev.target?.result as string) || "");
    };
    reader.readAsText(file);
  }

  function downloadReport() {
    if (!report) return;
    const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>QA Report</title>
<style>body{font-family:'DM Sans',sans-serif;max-width:800px;margin:40px auto;padding:20px;color:#1a2740}
.pass{color:#16a34a}.fail{color:#dc2626}.score{font-size:48px;font-weight:bold}
.section{border:1px solid #e2e8f0;border-radius:12px;margin:20px 0;padding:20px}
.check{padding:8px 0;border-bottom:1px solid #f1f5f9;display:flex;justify-content:space-between}
.badge{padding:2px 8px;border-radius:4px;font-size:12px}
.blocker{background:#fef2f2;color:#dc2626}.warning{background:#fffbeb;color:#d97706}.optimization{background:#eff6ff;color:#2563eb}
</style></head><body>
<h1>BVM Design Center — QA Report</h1>
<p class="score ${report.score >= 80 ? "pass" : "fail"}">${report.score}/100</p>
<p>Status: ${report.passed ? "PASSED" : "FAILED"} | Run: ${new Date(report.runAt).toLocaleString()}</p>
${report.passes
  .map(
    (p) => `<div class="section"><h2>${p.name} — <span class="${p.passed ? "pass" : "fail"}">${p.passed ? "Passed" : "Failed"}</span></h2>
${p.checks
  .map(
    (c) =>
      `<div class="check"><span>${c.passed ? "✓" : "✕"} ${c.name}: ${c.message}</span><span class="badge ${c.severity}">${c.severity}${c.autofix ? " ⚡" : ""}</span></div>`
  )
  .join("")}</div>`
  )
  .join("")}
<footer><p style="color:#94a3b8;margin-top:40px">Generated by BVM Design Center QA Engine</p></footer>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `qa-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function attachToProfile() {
    if (!attachClientId || !report) return;
    await fetch("/api/qa/run", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ htmlContent, clientId: attachClientId }),
    });
    setAttachClientId("");
  }

  const passNames = ["Checking structure...", "Checking compliance...", "Checking performance...", "Checking content..."];

  if (!authChecked) {
    return (
      <div style={{ minHeight: "100vh", background: "#0d1a2e", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div style={{ width: 32, height: 32, border: "2px solid #F5C842", borderTopColor: "transparent", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", background: "#0d1a2e", display: "flex", flexDirection: "column" }}>
      <TopNav activePage="qa" />

      <main style={{ flex: 1, padding: "40px 20px", maxWidth: 860, margin: "0 auto", width: "100%" }}>
        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: 32 }}>
          <h1
            style={{
              fontFamily: "'Playfair Display', Georgia, serif",
              fontSize: 36,
              fontWeight: 700,
              color: "#fff",
              margin: 0,
            }}
          >
            QA Engine
          </h1>
          <p style={{ fontSize: 14, color: "#94a3b8", marginTop: 8 }}>
            Automated four-pass validation for any HTML file
          </p>
        </div>

        {!report && !loading && (
          <div style={{ background: "#1a2740", border: "1px solid #243454", borderRadius: 12, padding: 32 }}>
            {/* Mode Toggle */}
            <div style={{ display: "flex", gap: 4, marginBottom: 24 }}>
              <button
                onClick={() => setMode("paste")}
                style={{
                  padding: "8px 20px",
                  borderRadius: 9999,
                  fontSize: 13,
                  fontWeight: 600,
                  border: "none",
                  cursor: "pointer",
                  background: mode === "paste" ? "#F5C842" : "#0d1a2e",
                  color: mode === "paste" ? "#0d1a2e" : "#94a3b8",
                }}
              >
                Paste HTML
              </button>
              <button
                onClick={() => setMode("upload")}
                style={{
                  padding: "8px 20px",
                  borderRadius: 9999,
                  fontSize: 13,
                  fontWeight: 600,
                  border: "none",
                  cursor: "pointer",
                  background: mode === "upload" ? "#F5C842" : "#0d1a2e",
                  color: mode === "upload" ? "#0d1a2e" : "#94a3b8",
                }}
              >
                Upload File
              </button>
            </div>

            {mode === "paste" ? (
              <textarea
                value={htmlContent}
                onChange={(e) => setHtmlContent(e.target.value)}
                placeholder="Paste your HTML here..."
                style={{
                  width: "100%",
                  minHeight: 320,
                  background: "#0d1a2e",
                  border: "1px solid #243454",
                  borderRadius: 10,
                  padding: 16,
                  fontFamily: "'DM Mono', monospace",
                  fontSize: 13,
                  color: "#fff",
                  resize: "vertical",
                  outline: "none",
                  boxSizing: "border-box",
                }}
              />
            ) : (
              <div
                style={{
                  border: "2px dashed #F5C842",
                  borderRadius: 12,
                  background: "#0d1a2e",
                  padding: "48px 20px",
                  textAlign: "center",
                }}
              >
                <p style={{ color: "#64748b", fontSize: 14, margin: "0 0 16px" }}>
                  Drop .html or .zip file here
                </p>
                <label
                  style={{
                    display: "inline-block",
                    background: "#243454",
                    color: "#fff",
                    padding: "8px 20px",
                    borderRadius: 8,
                    fontSize: 13,
                    fontWeight: 500,
                    cursor: "pointer",
                  }}
                >
                  Choose File
                  <input
                    type="file"
                    accept=".html,.htm,.zip"
                    onChange={handleFileUpload}
                    style={{ display: "none" }}
                  />
                </label>
                {htmlContent && (
                  <p style={{ color: "#22c55e", fontSize: 13, marginTop: 16 }}>
                    File loaded ({htmlContent.length.toLocaleString()} characters)
                  </p>
                )}
              </div>
            )}

            <button
              onClick={runQA}
              disabled={!htmlContent.trim()}
              style={{
                width: "100%",
                marginTop: 20,
                padding: "14px 0",
                borderRadius: 10,
                border: "none",
                background: "#F5C842",
                color: "#0d1a2e",
                fontSize: 14,
                fontWeight: 700,
                cursor: htmlContent.trim() ? "pointer" : "not-allowed",
                opacity: htmlContent.trim() ? 1 : 0.5,
              }}
            >
              Run QA →
            </button>
          </div>
        )}

        {/* Loading Animation */}
        {loading && (
          <div style={{ background: "#1a2740", border: "1px solid #243454", borderRadius: 12, padding: 32 }}>
            <h2 style={{ textAlign: "center", fontSize: 18, fontWeight: 600, color: "#fff", marginBottom: 24 }}>
              Running 4-pass QA...
            </h2>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {passNames.map((name, i) => (
                <div key={name} style={{ display: "flex", alignItems: "center", gap: 12 }}>
                  <div
                    style={{
                      width: 24,
                      height: 24,
                      borderRadius: "50%",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      fontSize: 11,
                      fontWeight: 700,
                      background:
                        loadingStep > i
                          ? "#22c55e"
                          : loadingStep === i
                            ? "transparent"
                            : "#334155",
                      color:
                        loadingStep > i ? "#fff" : "#64748b",
                      border:
                        loadingStep === i
                          ? "2px solid #F5C842"
                          : "none",
                      borderTopColor:
                        loadingStep === i ? "transparent" : undefined,
                      animation:
                        loadingStep === i ? "spin 1s linear infinite" : "none",
                    }}
                  >
                    {loadingStep > i ? "✓" : ""}
                  </div>
                  <span
                    style={{
                      fontSize: 13,
                      color:
                        loadingStep > i
                          ? "#22c55e"
                          : loadingStep === i
                            ? "#F5C842"
                            : "#64748b",
                    }}
                  >
                    {name}
                    {loadingStep > i && " Complete"}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Report */}
        {report && !loading && (
          <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            {/* Score Badge */}
            <div style={{ display: "flex", alignItems: "center", gap: 20, background: "#1a2740", border: "1px solid #243454", borderRadius: 12, padding: 24 }}>
              <div
                style={{
                  width: 88,
                  height: 88,
                  borderRadius: 16,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: 32,
                  fontWeight: 700,
                  color: "#fff",
                  background: report.score >= 80 ? "#22c55e" : report.score >= 50 ? "#f59e0b" : "#ef4444",
                }}
              >
                {report.score}
              </div>
              <div>
                <p style={{ fontSize: 20, fontWeight: 700, color: "#fff", margin: 0 }}>
                  {report.passed ? "QA Passed" : "QA Failed"}
                </p>
                <p style={{ fontSize: 13, color: "#64748b", margin: "4px 0 0" }}>
                  {report.passes.reduce((s, p) => s + p.checks.filter((c) => c.passed).length, 0)} of{" "}
                  {report.passes.reduce((s, p) => s + p.checks.length, 0)} checks passed
                </p>
              </div>
            </div>

            {/* Pass Sections */}
            {report.passes.map((pass) => (
              <div key={pass.name} style={{ background: "#1a2740", border: "1px solid #243454", borderRadius: 12, overflow: "hidden" }}>
                <button
                  onClick={() => setExpandedPass(expandedPass === pass.name ? null : pass.name)}
                  style={{
                    width: "100%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    padding: "14px 20px",
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <span style={{ color: pass.passed ? "#22c55e" : "#ef4444" }}>
                      {pass.passed ? "✓" : "✕"}
                    </span>
                    <span style={{ fontSize: 14, fontWeight: 600, color: "#fff" }}>{pass.name}</span>
                    <span style={{ fontSize: 12, color: "#64748b" }}>
                      {pass.checks.filter((c) => c.passed).length}/{pass.checks.length}
                    </span>
                  </div>
                  <span style={{ color: "#64748b" }}>{expandedPass === pass.name ? "▲" : "▼"}</span>
                </button>
                {expandedPass === pass.name && (
                  <div style={{ borderTop: "1px solid #243454" }}>
                    {pass.checks.map((check) => (
                      <div
                        key={check.name}
                        style={{
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "space-between",
                          padding: "10px 20px",
                          borderBottom: "1px solid #1e293b",
                        }}
                      >
                        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                          <span style={{ color: check.passed ? "#22c55e" : "#ef4444" }}>
                            {check.passed ? "✓" : "✕"}
                          </span>
                          <div>
                            <p style={{ fontSize: 13, color: "#fff", margin: 0 }}>{check.name}</p>
                            <p style={{ fontSize: 11, color: "#64748b", margin: "2px 0 0" }}>{check.message}</p>
                          </div>
                        </div>
                        <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                          <span
                            style={{
                              fontSize: 11,
                              padding: "2px 8px",
                              borderRadius: 4,
                              background:
                                check.severity === "blocker"
                                  ? "rgba(239,68,68,0.15)"
                                  : check.severity === "warning"
                                    ? "rgba(245,158,11,0.15)"
                                    : "rgba(59,130,246,0.15)",
                              color:
                                check.severity === "blocker"
                                  ? "#ef4444"
                                  : check.severity === "warning"
                                    ? "#f59e0b"
                                    : "#3b82f6",
                            }}
                          >
                            {check.severity}
                          </span>
                          {check.autofix && (
                            <span style={{ fontSize: 11, padding: "2px 8px", borderRadius: 4, background: "rgba(34,197,94,0.15)", color: "#22c55e" }}>
                              ⚡ auto-fix
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}

            {/* Actions */}
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
              <button
                onClick={downloadReport}
                style={{
                  background: "#F5C842",
                  color: "#0d1a2e",
                  border: "none",
                  padding: "10px 20px",
                  borderRadius: 8,
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                Download QA Report
              </button>
              <button
                onClick={() => { setReport(null); setHtmlContent(""); }}
                style={{
                  background: "transparent",
                  color: "#94a3b8",
                  border: "1px solid #243454",
                  padding: "10px 20px",
                  borderRadius: 8,
                  fontSize: 13,
                  fontWeight: 500,
                  cursor: "pointer",
                }}
              >
                Run Another
              </button>
            </div>

            {/* Attach to Profile */}
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <select
                value={attachClientId}
                onChange={(e) => setAttachClientId(e.target.value)}
                style={{
                  background: "#0d1a2e",
                  border: "1px solid #243454",
                  borderRadius: 8,
                  padding: "8px 14px",
                  fontSize: 13,
                  color: "#fff",
                  outline: "none",
                }}
              >
                <option value="">Attach to Profile...</option>
                {clients.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.business_name}
                  </option>
                ))}
              </select>
              {attachClientId && (
                <button
                  onClick={attachToProfile}
                  style={{
                    background: "#243454",
                    color: "#fff",
                    border: "none",
                    padding: "8px 16px",
                    borderRadius: 8,
                    fontSize: 13,
                    fontWeight: 600,
                    cursor: "pointer",
                  }}
                >
                  Attach
                </button>
              )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
